[M-STEPSTB]  # <tracker-name>
label = M-STEPSTB
protocol = traxpython
command = M-STEPSTB
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = ''
