[OSTrackSTB]  # <tracker-name>
label = OSTrackSTB
protocol = traxpython
command = OSTrackSTB
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /home/yebotao/OSTrack/lib/test/vot22
