[ODTrackSTB]  # <tracker-name>
label = ODTrackSTB
protocol = traxpython
command = ODTrackSTB
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = /home/guest/wangyujie/ODTrack/lib/test/vot22
